spring.application.name=auth-server

keycloak.auth-server-url=http://localhost:9999
keycloak.realm=test
keycloak.client-id=final
keycloak.client-secret=NOgGcgcnyHLNXBrhUQuHfqVxwlKxlHFs


# Keycloak Configuration
keycloak.bearer-only=true
keycloak.public-client=true
keycloak.ssl-required=external
keycloak.use-resource-role-mappings=true


server.port=10000