spring:
  application:
    name: apigateway
  cloud:
    gateway:
      httpclient:
        connectTimeout: 1000  # 1000ms== 1s, its the time required to connect to the downstream app
        responseTimeout: 5s   # its the time required to recieve response
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s


# Eureka Configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

server:
  port: 8051

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:  # Can add the name of circuit breaker for different properties
        slidingWindowSize: 10   # No of requirests to be monitored before opening the circuit
        failureRateThreshold: 50  # 50% of requests if fails, then circuit needs to be open
        permittedNumberOfCallsInHalfOpenState: 2  # Periodically number of calls to pass to check
        waitDurationInOpenState: 10000  # Time application should be in open state before going to half open state
