spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3307/learnDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud: # For circuitbreaker
    openfeign:
      circuitbreaker:
        enabled: true
  config:
    import: optional:configserver:http://localhost:8071/
    # optional denotes that the MS should start even if config server is not running.
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest
  sql:
    init:
      mode: always
server:
  port: 8081

# Eureka Configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

root:
  name: Root1
  game: pubg

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        tags:
          application: accounts
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"
  level:
    com:
      learning:
        accounts: DEBUG

endpoint:
  shutdown:
    enabled: true

info:
  app:
    name: "Accounts MS"
    description: "Accounts Micro-Services for Application"
    version: "1.0.0"

resilience4j:
  circuitbreaker:
    configs:
      default:  # Can add the name of circuit breaker for different properties
        slidingWindowSize: 10   # No of requirests to be monitored before opening the circuit
        failureRateThreshold: 50  # 50% of requests if fails, then circuit needs to be open
        permittedNumberOfCallsInHalfOpenState: 2  # Periodically number of calls to pass to check
        waitDurationInOpenState: 10000  # Time application should be in open state before going to half open state
