spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8071/
    # optional denotes that the MS should start even if config server is not running.

server:
  port: 8081

root:
  name: Root1
  game: pubg

